name: sexomics_nf
channels:
  - conda
  - conda-forge
  - bioconda
  - anaconda
  - dranew
dependencies:
  # Binary dependencies / tools.
  - nextflow>=0.30.1
  - bcl2fastq
  - pigz
  - star
  - trim-galore
  - cutadapt
  - samtools
  - bedtools
  - bamtools
  - datamash

  # Python and modules.
  - pypy3.9==7.3.11
  - biopython==1.78
  - matplotlib
  - scipy
  - hdf5
  - pysam

  # R and libraries
  - r-base>=4.2.2
  - r-ggplot2
  - r-argparse
  - r-jsonlite
  - r-shiny
  - r-stringr
  - r-terra
  - r-monocle3
  - scrublet

  # C/Make dependencies.
  - proj==9.1.1
  - gdal
  - fmt
  - libgcc-ng
  - pcre2
  - zlib
  - openssl
