name: sexomics_nf
channels:
  - conda-forge
  - bioconda

dependencies:
  # Binary dependencies / tools.
  - bioconda::nextflow
  - dranew::bcl2fastq
  - conda-forge::pigz
  - bioconda::star
  - bioconda::trim-galore
  - bioconda::cutadapt>=4.2
  - bioconda::samtools
  - bioconda::bedtools
  - bioconda::bamtools
  - conda-forge::datamash

  # Python and modules.
  - conda-forge::python>=3.0.0
#  - conda-forge::pypy
  - conda-forge::biopython
  - conda-forge::matplotlib
  - conda-forge::scipy
  - conda-forge::hdf5
  - bioconda::pysam

  # R and libraries
  - conda-forge::r-base>=4.1.0
  - conda-forge::r-ggplot2
  - conda-forge::r-argparse
  - conda-forge::r-jsonlite
  - conda-forge::r-shiny
  - conda-forge::r-stringr
  - conda-forge::r-terra>=1.7_18
  - bioconda::r-monocle3
  - bioconda::scrublet
  - conda-forge::numba

  # C/Make dependencies.
  - conda-forge::proj
  - conda-forge::fmt
  - conda-forge::libgcc-ng
  - conda-forge::pcre2
